# Generated by Django 5.1.3 on 2025-02-23 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='setor',
            new_name='nome_setor',
        ),
    ]
